name: birthday_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  video_player: ^2.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
     - images/home.jpg
     - images/livingroom.jpg
     - images/roseplant.jpg
     - images/image1.jfif
     - images/image2.jfif
     - images/image3.jfif
     - videos/sample.mp4
  fonts:
    - family: Pina Colada
      fonts:
        - asset: fonts/Pina_Colada.ttf
